require("plugins")
require("options")
require("dracula-config")
-- require("solarized-config")
require("colorschemes")
require("keybindings")
require("whichkey-config")
require("bufferline-config")
-- require("stabline-config")
-- require("lualine-config")
-- require("treesitter-config")
require("nvim-tree-config")
require("autopairs-config")
require("blankline-config")
require("colorizer-config")
require("comment-config")
require("dashboard-config")
require("lsp")
require("lspsaga-config")
require("null-ls-config")
require("telescope-config")
require("toggleterm-config")

vim.cmd([[source ~/.config/nvim/fold-config/config.vim]])
vim.cmd([[hi Normal guibg=NONE ctermbg=NONE]])
vim.cmd([[let &t_ZH="\e[3m"]])
vim.cmd([["let &t_ZR="\e[23m"]])
